DESCRIPTION

MB-0 result should be equal or
smaller number expected.

Change-Id: I7b52cee0c807183b27830d55e84d7c0cdacdc433


COMMENTS

author: Porter Oconnor
date: 2013-09-02 15:54:08.254000000

Patch Set 1:

(1 comment)

Line:236, pytests/viewmergetests.py -> Tony, thanks for looking at this.

From the build bot e-mail failure of August 29, I see the message:

"Stack Trace:
['Traceback (most recent call last):\n  File "pytests/viewmergetests.py", line 161, in test_dev_view\n    self.verify_results_dev(results)\n  File "pytests/viewmergetests.py", line 240, in verify_results_dev\n    % (len(expected), len(results.get(u\'rows\', [])))))\nAssertionError: Rows number is wrong, expected to be lower than 6400 and >0, but it was 6405\n']"

So this change doesn't fix it, as the difference is +5 and not +1.
Also, when did this test started to fail for the first time? Is it really a test issue or in the server? Did the failure happened immediately after the test was changed, or not (in this case it's likely a server issue) ?

-------------------------------------
