DESCRIPTION

CBQE-1531: add failover+ server failure test

Change-Id: Ia2b7698ff14d41117d325fcee223b24a82aeabb0


COMMENTS

author: Esperanza Cherry
date: 2013-10-10 09:28:19.035000000

Patch Set 1:

(1 comment)

Line:106, pytests/tuqquery/tuq_cluster_ops.py -> I guess remote may be outside of the loop and use disconnect() + self.master

-------------------------------------
