DESCRIPTION

Improve error handling of PullOperation

Catch JGitInternalException and unpack cause
to provide proper error message.

Change-Id: I4ff57cbfa90bd3d0cfe2ec105407400fd14d8d9d
Signed-off-by: Marlie Beasley xxx@xxx.xxx


COMMENTS

author: Juliet Cantu
date: 2011-01-14 13:01:15.000000000

Patch Set 1: I would prefer that you didn't submit this

(1 inline comment)



Line:71, org.eclipse.egit.core/src/org/eclipse/egit/core/op/PullOperation.java -> 1) When would getCause return null?

2) Why drop the exeption message and use the cause' message?

-------------------------------------
author: Marlie Beasley
date: 2011-01-14 13:20:19.000000000

Patch Set 1: (1 inline comment)



-------------------------------------
author: Juliet Cantu
date: 2011-01-14 13:30:03.000000000

Patch Set 1: (1 inline comment)



Line:71, org.eclipse.egit.core/src/org/eclipse/egit/core/op/PullOperation.java -> ok for 1) getCause can return null (even though the field cause is never null).

2) But e.getMessage also contains information, so I believe that message should be reported and e passed to error,  just like GitAPIException is handled.

-------------------------------------
author: Marlie Beasley
date: 2011-01-14 13:53:28.000000000

Patch Set 1: (1 inline comment)



Line:71, org.eclipse.egit.core/src/org/eclipse/egit/core/op/PullOperation.java -> Done

-------------------------------------
author: Marlie Beasley
date: 2011-01-14 13:20:18.000000000

MISMATCHED INLINE COMMENT
Line:71, org.eclipse.egit.core/src/org/eclipse/egit/core/op/PullOperation.java -> 1) is a safety net. It is possible to construct this exception without cause.
2) The cause is the interesting thing here. If contains the error information when push failed.

-------------------------------------
