DESCRIPTION

Throw formal CheckoutConflictException on hard reset

This will allow calling classes to have access to the
conflicts that occurred during the attempted checkout.

Even though setFailOnConflict(false) is called on the
DirCacheCheckout a CheckoutConflictException can still
be thrown if cleanup fails.

Change-Id: Iea7ad3176a1b0e8606a643de8945e276718eb3ce


COMMENTS

author: Juliet Cantu
date: 2012-06-04 21:33:52.000000000

Patch Set 1:

Can you please add the exception to the throws list in the call method too.

-------------------------------------
