DESCRIPTION

Catch IOException in ConfigureGerritAfterCloneTask

This task must not make the git clone be reported as failed -- the
repository was already successfully cloned. Catch the exception and
return false, which is the safe thing to do: in the worst case, the
user may have to do the Gerrit config setup him- or herself via the
ConfigureGerritWizard.

Also clean up closing streams and disconnecting.

Bug: 494342
Change-Id: Ie10cb12da8e8d732c956e7352c15702898e23710
Signed-off-by: Alayna Houston xxx@xxx.xxx

COMMENTS

author: Alayna Houston
date: 2016-05-23 20:06:38.000000000

Uploaded patch set 1.

-------------------------------------
author: Brenden Conley
date: 2016-05-23 20:06:44.000000000

Patch Set 1:

Build Started https://hudson.eclipse.org/egit/job/egit.gerrit/8617/

-------------------------------------
author: Brenden Conley
date: 2016-05-23 20:31:48.000000000

Patch Set 1: Code-Review-1

Build Unstable 

https://hudson.eclipse.org/egit/job/egit.gerrit/8617/ : UNSTABLE

-------------------------------------
author: Brenden Conley
date: 2016-05-23 20:57:46.000000000

Patch Set 1: -Code-Review

Build Started https://hudson.eclipse.org/egit/job/egit.gerrit/8619/

-------------------------------------
author: Brenden Conley
date: 2016-05-23 21:22:47.000000000

Patch Set 1: Verified+1

Build Successful 

https://hudson.eclipse.org/egit/job/egit.gerrit/8619/ : SUCCESS

-------------------------------------
author: Douglas Trujillo
date: 2016-05-23 23:24:55.000000000

Patch Set 1:

(1 comment)

Line:209, org.eclipse.egit.core/src/org/eclipse/egit/core/op/ConfigureGerritAfterCloneTask.java -> maybe log a warning ?

-------------------------------------
author: Alayna Houston
date: 2016-05-24 04:49:05.000000000

Patch Set 1:

(1 comment)

Line:209, org.eclipse.egit.core/src/org/eclipse/egit/core/op/ConfigureGerritAfterCloneTask.java -> Why? I did think about doing so and in the end decided against it. The ssh part below also doesn't do so.

My reasoning for not logging it is:
* since we just cloned successfully, it shouldn't happen.
* if it happens and the server is a Gerrit, it's most likely a transient thing (like the timeout in the bug report).
* if it's not a Gerrit, the user will get a spurious warning.
* the user can re-try later through the Gerrit Configuration wizard.

What would be your reasons for logging here?

-------------------------------------
author: Douglas Trujillo
date: 2016-05-24 06:34:02.000000000

Patch Set 1: Code-Review+2

-------------------------------------
author: Gerrit Johnathan Pham
date: 2016-05-24 06:34:09.000000000

Change has been successfully merged into the git repository by Douglas Trujillo

-------------------------------------
