DESCRIPTION

CBQE: 2594 fix bug in task identification

Change-Id: I87600b30067a72a4fdb0bff9ce876a41e278dbf6


COMMENTS

author: Ezekiel Beck
date: 2015-02-13 22:48:16.838000000

Uploaded patch set 1.

-------------------------------------
author: Hugo Blankenship
date: 2015-02-13 22:48:24.593000000

Patch Set 1:

Build Started http://factory.couchbase.com/job/testrunner-Jasmin Rangel-sherlock/4193/

-------------------------------------
author: Hugo Blankenship
date: 2015-02-13 23:07:18.159000000

Patch Set 1: Verified+1

Build Successful 

http://factory.couchbase.com/job/testrunner-Jasmin Rangel-sherlock/4193/ : SUCCESS

-------------------------------------
author: Titus Ho
date: 2015-02-13 23:22:37.773000000

Patch Set 1: Code-Review-1

(3 comments)

Thanks Emerson Duke, some comments here... also were you able to verify this in 3.0.2?

Line:2293, lib/tasks/task.py -> I think it's possible to have type = 'indexer' for both 'designDocument' and 'design_documents' target, correct?

whatever is set here can just be considered default
(see possible resolution below)

Line:2298, lib/tasks/task.py -> "designDocument?"

Line:2317, lib/tasks/task.py -> Here' check if "design_document" exists in task, change self.target_key to fallback:

self.target_key = "design_documents"

-------------------------------------
author: Tate Garrett
date: 2015-02-19 22:10:30.645000000

Change has been successfully cherry-picked as 347d897ddfcfd51f26e333df06a16a950209ea67

-------------------------------------
