DESCRIPTION

Retry memcached writes when not_my_vbucket thrown

Change-Id: I92250d298d5405ea9bc734888505a8714aab2d90


COMMENTS

author: Julianne Schultz
date: 2011-07-22 21:11:44.381000000

Uploaded patch set 6.

-------------------------------------
author: Nathalie Landry
date: 2011-07-23 11:17:23.353000000

Patch Set 6:

Have you tried this during rebalance? I bet it would fail. Because simply retrying against (most likely) same vbucket map  will not work.

-------------------------------------
author: Julianne Schultz
date: 2011-07-24 21:51:18.471000000

Patch Set 6:

I asked a bunch of people for the best mechanism for retrying when not_my_vbucket and got various inconclusive answers, some said try all the vbuckets twice, some said retry, the code just retries 10 times but its mechanism could be changed if I knew what the correct way was.

-------------------------------------
author: Nathalie Landry
date: 2011-07-24 22:04:02.027000000

Patch Set 6:

well it needs to work under rebalance. We'll need same logic as any smart client has, apparently. Which is:

a) try node from vbucket map

b) if that fails try node from fast forward map if it exists

c) try all other nodes in turn

We can do some additional goodness like syncing on config replication after a) and/or and then retrying a and b once if vbucket map was changed.

-------------------------------------
author: Julianne Schultz
date: 2011-07-25 00:30:02.563000000

Patch Set 6: Fails



-------------------------------------
