DESCRIPTION

CBQE-265: reset_vbucket when poxi does not have mc connection during rebalance out

attempt to reset_vbucket when poxi does not have a mc connection during rebalance out

Change-Id: Ic9c3aea4e2b1862b9970bc75e29821dc931692ea


COMMENTS

author: Hugo Blankenship
date: 2012-06-21 22:30:46.850000000

Patch Set 1:

Build Started http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/1100/ 

-------------------------------------
author: Titus Ho
date: 2012-06-21 22:40:38.429000000

Patch Set 1:

is poxy a 'moxy' typo or something else?

-------------------------------------
author: Hugo Blankenship
date: 2012-06-21 22:46:15.519000000

Patch Set 1: Verified

Build Successful 

http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/1100/ : SUCCESS

-------------------------------------
author: Reid Stokes
date: 2012-06-21 23:20:06.748000000

Patch Set 1: (1 inline comment)

Also, its moxi

Line:845, lib/memcached/helper/data_helper.py -> I dont think this "poxi does not have a mc connection for server" is needed to be printed out..
you just need to print error.message

-------------------------------------
author: Esperanza Cherry
date: 2012-06-22 02:33:25.047000000

Patch Set 1: Fails

skip now to reproduce for details

-------------------------------------
author: Zackery Barr
date: 2012-06-27 05:22:34.330000000

Patch Set 1: Looks good to me, approved

(1 inline comment)



Line:845, lib/memcached/helper/data_helper.py -> yes lets just print the error and retry

-------------------------------------
author: Esperanza Cherry
date: 2012-06-29 19:21:13.109000000

Patch Set 1: Abandoned

-------------------------------------
