DESCRIPTION

Added new tests for Autofailover related scenarios.
    1. Added tests for autofailover of nodes and validation of the failover for the following scenarios
            "firewall": enable_firewall,
            "stop_server": stop_couchbase_server,
            "restart_server": restart_couchbase_server,
            "restart_machine": restart_machine,
            "restart_network": stop_restart_network,
            "stop_memcached": stop_memcached,
            "network_split": split_network
    2. Added tests for autofailover with rebalance of nodes, with rebalance in progress, rebalance before failure, rebalance after failure.
    3. Added tests for autofailover of nodes and add back of nodes
    4. Added tests for autofailover of nodes with removal of nodes after failover
    5. Added methods to inject different failures into the system and validate the expected autofailover in the given time

Change-Id: Ie93b3330d5aa030189636dbca154a383a81c5a11


COMMENTS

author: Lucille Zavala
date: 2017-03-03 12:40:37.176000000

Uploaded patch set 2.

-------------------------------------
author: Lucille Zavala
date: 2017-03-03 12:42:25.734000000

Patch Set 2:

(1 comment)

-------------------------------------
author: Titus Ho
date: 2017-03-03 15:44:25.811000000

Patch Set 2:

(4 comments)

Line:18, lib/membase/api/rest_client.py -> remove unused imports

Line:14, lib/tasks/task.py -> re-organing the imports adds unnecessary diffs.  Unless something here is new (+needed) please leave the ordering same and change in separate commit

Line:4570, lib/tasks/task.py -> replace:  0<=self.pause < self.timeout

as I'm assuming even if pause is 0, but we've exceeded timeout you want to quit

Line:417, lib/remote/remote_util.py -> Any reason for not doing a stop and then a start here?  ie...

self.stop_server()
self.start_server()

-------------------------------------
author: Emely Wilson
date: 2017-03-06 06:00:57.369000000

Patch Set 2: Code-Review+1

-------------------------------------
author: Lucille Zavala
date: 2017-03-06 11:24:48.764000000

Patch Set 2:

(4 comments)

Line:18, lib/membase/api/rest_client.py -> Done

Line:14, lib/tasks/task.py -> Done

Line:4570, lib/tasks/task.py -> Done

Line:417, lib/remote/remote_util.py -> This is for testing the restart command of the service specifically and hence not using self.stop_server() and self.start_server() even though internally they are the same.

-------------------------------------
