DESCRIPTION

MB-9694: Fix crash caused by creating two same named upr conns

When we have an upr connection with a given name and another upr
connection is made with the same name then we need to close the
first connection and allow the second one to be created.

Change-Id: I0346b70f395b3d8c29f5288ffc7ecd5cc36a7700


COMMENTS

author: Kenny Maynard
date: 2014-02-19 23:22:44.645000000

Uploaded patch set 7.

-------------------------------------
author: Titus Ho
date: 2014-02-21 16:14:03.327000000

Patch Set 7:

Hey Mike,  you're probably aware of this but just fyi this patch is bringing about much regression in pyupr for some reason.  Also test_stream_request_multiple_vbuckets hangs.

-------------------------------------
author: Kenny Maynard
date: 2014-02-21 19:48:42.734000000

Patch Set 7: Verified-1

I'll double check the code. I don't recall seeing errors on my side.

-------------------------------------
author: Kenny Maynard
date: 2014-02-21 20:24:12.010000000

Patch Set 7: Verified+1

This change does work. I think Tommie grabbed the two dependent changes and one of those changes relies on a memcached patch which he did not have.

-------------------------------------
author: Titus Ho
date: 2014-02-21 20:31:04.454000000

Patch Set 7: Verified+1

right, applied corresponding to memcached branch and everything's fine (http://review.Piper Jefferson.org/#/c/33480/1)

-------------------------------------
author: Abby Duran
date: 2014-02-26 21:23:00.892000000

Patch Set 7: Code-Review+2

-------------------------------------
