DESCRIPTION

CBQE-362: start nodes after failover spatialviews tests

added in finally block restart failover servers

Change-Id: I94ceff3af6e703b66774f91d72ccb304d8a2df2f


COMMENTS

author: Esperanza Cherry
date: 2012-07-24 21:38:02.930000000

Uploaded patch set 3.

-------------------------------------
author: Jasmin Rangel
date: 2012-07-24 21:38:04.685000000

Patch Set 3:

New patchset patch-id matches previous patchset, but commit message has changed.

-------------------------------------
author: Hugo Blankenship
date: 2012-07-24 21:51:57.953000000

Patch Set 3:

Build Started http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/1915/ 

-------------------------------------
author: Hugo Blankenship
date: 2012-07-24 22:08:49.928000000

Patch Set 3: Verified

Build Successful 

http://qa.hq.northscale.net/job/testrunner-Jasmin Rangel-master/1915/ : SUCCESS

-------------------------------------
author: Ayla Reynolds
date: 2012-07-24 22:12:31.953000000

Patch Set 3: (1 inline comment)

Sorry that I haven't caught this in an earlier review.

Line:92, lib/membase/helper/failover_helper.py -> For my taste that's too many list comprehensions nested.

I think it's way more understandable with normal loops. Isn't this just (please note that I haven't tested that):

    for server in self.servers:
        for node in nodes:
            if node.ip == server.ip and str(node.port) == server.port:
                shell = RemoteMachineShellConnection(server)
                shell.start_couchbase()

-------------------------------------
