DESCRIPTION

Rebalance With FailOver with Parallel Load

Change-Id: Iedee181ffc95d431c54f60175042d3ec15d98b64


COMMENTS

author: Reid Stokes
date: 2012-04-25 00:44:57.182000000

Patch Set 1: (3 inline comments)



Line:14, conf/py-181-kv-rebalance-tests.conf -> keys-count=30000 is default i think.. makes it redudant

Line:286, lib/tasks/task.py -> You also need to change the rest client to raise an exception if the fail_over fails.. which is not there right now

Line:301, lib/tasks/task.py -> this does nto return progress.

-------------------------------------
author: Amani Conrad
date: 2012-04-25 02:18:53.926000000

Patch Set 1: Abandoned

-------------------------------------
