DESCRIPTION

CBQE-1739: added test to verify fix for MB-9693

Change-Id: I590466f985ed2850243775baa077d26a9687c534


COMMENTS

author: Fisher Vargas
date: 2014-02-11 13:15:38.273000000

Uploaded patch set 15.

-------------------------------------
author: Hugo Blankenship
date: 2014-02-11 16:02:17.437000000

Patch Set 15:

Build Started http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/460/

-------------------------------------
author: Hugo Blankenship
date: 2014-02-11 16:28:51.157000000

Patch Set 15: Verified-1

Build Failed 

http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/460/ : FAILURE

-------------------------------------
author: Angelina Mayer
date: 2014-02-11 17:32:15.315000000

Patch Set 15: Code-Review-1

(2 comments)

Line:115, pytests/xdcr/xdcrMiscTests.py -> 'else' is not indented against if. why is there a break at end of for? the break inside if should do, else we continue.

Line:118, pytests/xdcr/xdcrMiscTests.py -> The test does not check if 'enoent' has been encountered. Enoent does not always result in data mismatch. So if we dont have that check, this test is as good as any other test in dgm scenario. Can we pls add that check?

Junyi, is there any API call that returns the xdcr errors?

-------------------------------------
author: Angelina Mayer
date: 2014-02-11 17:35:13.373000000

Patch Set 15:

Also, would be able to make the method name more meaningful - say instead of test_verify_mb9693, can we say test_verify_enoent so by just looking at the test we know what it will do. Now that we are going to be automating so many bug verifications, we will lose track of the mb number.

Thanks,
Aruna

-------------------------------------
author: Fisher Vargas
date: 2014-02-12 05:19:39.727000000

Patch Set 15:

(2 comments)

Line:115, pytests/xdcr/xdcrMiscTests.py -> Aruna, why else should be indented here?, last break is for while loop. No it will not work. when we continue, control goes to loop and when it will go to for loop and there is only 2 buckets then this will run only two times.

Line:118, pytests/xdcr/xdcrMiscTests.py -> As per the bug, enoent will cause the data loss/mismatch?. Please confirm from Junyi.

-------------------------------------
