DESCRIPTION

CBQE-2177:: Adding support for delta rebalance+some basic tests

Change-Id: I565c7a24adaa6b917a61e82617085161425862dc


COMMENTS

author: Quentin Ali
date: 2014-04-02 16:43:44.687000000

Uploaded patch set 3.

-------------------------------------
author: Quentin Ali
date: 2014-04-02 16:46:34.731000000

Patch Set 3:

do we need to set recovery type for all nodes that were failovered? or we can set type on master?
It is a fair question to ask. This can be set for any node. Per our design of test cases, we are doing the same recovery type. But can be full or delta. I think the design should allow one type to keep it simple. This would require more clarification from Alk.

-------------------------------------
author: Esperanza Cherry
date: 2014-04-02 16:56:58.588000000

Patch Set 3:

it's easy to check. do you know how to check/get recoveryType from node/cluster?

verification steps should be like:
1) cluster/nose with recoveryType A
2) set recoveryType B for node1

check whether recoveryType B applied to 1 node or to cluster.

" Per our design of test cases, we are doing the same recovery type" - it can be modified in a few lines, the main thing to get an answer to the previous question

-------------------------------------
author: Quentin Ali
date: 2014-04-02 17:06:15.740000000

Patch Set 3:

I have posted a question to Alk, you are cc'd on it. I will also add your suggestion to the test case. Thanks!

-------------------------------------
author: Hugo Blankenship
date: 2014-04-02 17:09:37.892000000

Patch Set 3:

Build Started http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/911/

-------------------------------------
author: Hugo Blankenship
date: 2014-04-02 17:21:51.027000000

Patch Set 3: Verified+1

Build Successful 

http://factory.couchbase.com/job/testrunner-Jasmin Rangel-master/911/ : SUCCESS

-------------------------------------
author: Fisher Vargas
date: 2014-04-03 15:44:03.451000000

Patch Set 3:

(4 comments)

Line:114, pytests/failover/failovertests.py -> space after comma in arguments.

Line:21, lib/membase/api/rest_client.py -> Where SetRecoveryTypeFailed exception is defined?

Line:965, lib/membase/api/rest_client.py -> space after comma in arguments.

Line:967, lib/membase/api/rest_client.py -> If both of these arguments are mandatory, then don't make it default arguments. 

def set_recovery_type(self, otpNode, recoveryType):

-------------------------------------
